var data= {
    "id": 0,
    "width": 300,
    "height": 100,    
    "fontFamily": "Arial",
    "fontSize": 20,
    "fontWeight": "normal",
    "text": "button",
    "color": "#ffffff",
    "backgroundBottom": "#007EE8",
    "backgroundTop": "#007FDA",
    "paddingTop": 4,
    "paddingRight": 4,
    "paddingBottom": 4,
    "paddingLeft": 4,
    "border": 2,
    "borderTop": "#ffffff",
    "borderRight": "#ffffff",
    "borderBottom": "#ffffff",
    "borderLeft": "#ffffff",
    "borderRadius": "10",
    "hoverColor": "#ffffff",
    "hoverBackground": "#565478",
    "activeColor": "#ffffff",
    "activeBackground": "#678765"
}